### PR TITLE
Doctrine 4 fix

### LINKED ISSUE #12: Doesn't work in Doctrine 4.0 and broken automated checks
# Calls to removed methods
#7 claimed to add support for Doctrine 4.0, but there are still multiple calls to removed `QueryBuilder::execute()` method (along with some calls to other removed methods) across the codebase.

# Broken automated checks
Cloning the repository and running the test suite results in 11/11 errors which means that the automated checks for the PR incorrectly passed. I took a glance at the [workflow file](https://github.com/php-casbin/dbal-adapter/actions/runs/9451081832/workflow) and I suspect this might be due to Composer package caching, which skipped the `Install dependencies` step and probably used an old version of Doctrine.

# Proposed solution
Fixing the source code itself isn't complicated and I might take a shot at it if I have time at some point, but I think fixing the tests should be the first priority, since that would've immediately detected the broken code. I also find it a bit odd that apparently no tests were run locally at any point.

### PR DESCRIPTION
**Pull request by Cryszon**
Fixes adapter not working in Doctrine 4. I only tested this in PHP 8.3 and Doctrine 4 (using in-memory SQLite DB instead of MySQL) so feel free to test on other PHP and Doctrine versions as well.

Fixes #12.

### CODE REVIEW

File: tests/AdapterTest.php [hunk 1]
```diff
@@ -1,50 +1,69 @@
...
+            $connConfig->setSQLLogger(new DebugStackLogger());
+        }
+        // Doctrine >= 4.0
+        else {
+            $connConfig->setMiddlewares([
+              new LoggingMiddleware(new PsrLogger())
+            ]);
+        }
+    }
+}
```
Comment (leeqvip) [inline tests/AdapterTest.php:69]: Please modify, do not change all lines

**Review by leeqvip — COMMENTED** [review]
Please modify, do not change all lines in Test file.

File: tests/AdapterTest.php (hunk 1 above)
Comment (Cryszon) [reply tests/AdapterTest.php:69]: This is due to different line endings (`CRLF` vs `LF`). I can try to fix it if you let me know which line endings this repository prefers, since there's no `.gitattributes` file.

The weird thing is that `Adapter.php` didn't show all lines as changed. Does this mean that test have a different line ending than the source code? I highly recommend adding a `.gitattributes` and normalizing all line endings if that's the case.

Comment (Cryszon) [reply tests/AdapterTest.php:69]: For the sake of reviewing the actual changes, I've attached diffs without whitespace changes for both files below:

```diff
diff --git a/tests/AdapterTest.php b/tests/AdapterTest.php
index b27f34a..1b5eb2a 100644
--- a/tests/AdapterTest.php
+++ b/tests/AdapterTest.php
@@ -6,10 +6,10 @@ use CasbinAdapter\DBAL\Adapter as DatabaseAdapter;
 use Doctrine\DBAL\Configuration;
 use Doctrine\DBAL\DriverManager;
 use Doctrine\DBAL\Exception;
+use Doctrine\DBAL\Logging\Middleware as LoggingMiddleware;
 
 class AdapterTest extends TestCase
 {
-
     /**
      * @throws Exception
      */
@@ -17,8 +17,7 @@ class AdapterTest extends TestCase
     {
         $this->initConfig();
         $connConfig = new Configuration();
-        $logger = new DebugStackLogger();
-        $connConfig->setSQLLogger($logger);
+        $this->configureLogger($connConfig);
         $conn = DriverManager::getConnection(
             $this->config,
             $connConfig
@@ -40,11 +39,31 @@ class AdapterTest extends TestCase
             ["p", "bob", "data", "write", "allow"]
         ], $oldRules);
 
-        $stmt = $conn->createQueryBuilder()->from($adapter->policyTableName)->where('p_type = "p" and v1 = "data" and v3 = "allow"')->select("v0", "v1", "v2", "v3")->execute();
+        $query = $conn->createQueryBuilder()->from($adapter->policyTableName)->where('p_type = "p" and v1 = "data" and v3 = "allow"')->select("v0", "v1", "v2", "v3");
+        $stmt = method_exists($query, "executeQuery") ? $query->executeQuery() : $query->execute();
         $result = method_exists($stmt, 'fetchAssociative') ? $stmt->fetchAllAssociative() : $stmt->fetchAll();
 
         $result = array_map([$adapter, "filterRule"], $result);
 
         $this->assertEquals($newPolicies, $result);
     }
+
+    /**
+     *
+     * @param \Doctrine\DBAL\Configuration $connConfig
+     * @return void
+     */
+    private function configureLogger($connConfig)
+    {
+        // Doctrine < 4.0
+        if(method_exists($connConfig, "setSQLLogger")) {
+            $connConfig->setSQLLogger(new DebugStackLogger());
+        }
+        // Doctrine >= 4.0
+        else {
+            $connConfig->setMiddlewares([
+              new LoggingMiddleware(new PsrLogger())
+            ]);
+        }
+    }
 }
```

```diff
diff --git a/tests/TestCase.php b/tests/TestCase.php
index f5371fa..eeb21b7 100644
--- a/tests/TestCase.php
+++ b/tests/TestCase.php
@@ -32,7 +32,8 @@ class TestCase extends \PHPUnit\Framework\TestCase
         $tableName = $adapter->policyTableName;
         $conn = $adapter->getConnection();
         $queryBuilder = $conn->createQueryBuilder();
-        $queryBuilder->delete($tableName)->where('1 = 1')->execute();
+        $query = $queryBuilder->delete($tableName)->where('1 = 1');
+        method_exists($query, "executeQuery") ? $query->executeQuery() : $query->execute();
 
         $data = [
             ['p_type' => 'p', 'v0' => 'alice', 'v1' => 'data1', 'v2' => 'read'],
@@ -42,7 +43,8 @@ class TestCase extends \PHPUnit\Framework\TestCase
             ['p_type' => 'g', 'v0' => 'alice', 'v1' => 'data2_admin'],
         ];
         foreach ($data as $row) {
-            $queryBuilder->insert($tableName)->values(array_combine(array_keys($row), array_fill(0, count($row), '?')))->setParameters(array_values($row))->execute();
+            $query = $queryBuilder->insert($tableName)->values(array_combine(array_keys($row), array_fill(0, count($row), '?')))->setParameters(array_values($row));
+            method_exists($query, "executeQuery") ? $query->executeQuery() : $query->execute();
         }
     }
```

**Review by leeqvip — APPROVED** [review]

**Comment by Cryszon** [comment]
Thank you! Just as a reminder, the files in the repository have mixed line endings (this was already a case for some files before this PR), so if anyone else submits PRs from non-Windows platforms, the diffs might not display correctly. As I mentioned before, I suggest normalizing everything to `LF`, but that's a housekeeping task that doesn't affect functionality.
